// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Episode struct {
	ID             pgtype.UUID        `json:"id"`
	SeasonID       pgtype.UUID        `json:"season_id"`
	EpisodeNumber  int32              `json:"episode_number"`
	Name           string             `json:"name"`
	Overview       string             `json:"overview"`
	AirDate        pgtype.Date        `json:"air_date"`
	RuntimeMinutes int32              `json:"runtime_minutes"`
	StillUrl       string             `json:"still_url"`
	ExternalID     string             `json:"external_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type LibraryItem struct {
	ID        pgtype.UUID        `json:"id"`
	MediaID   pgtype.UUID        `json:"media_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Medium struct {
	ID               pgtype.UUID        `json:"id"`
	Type             string             `json:"type"`
	Title            string             `json:"title"`
	OriginalTitle    string             `json:"original_title"`
	Year             pgtype.Int4        `json:"year"`
	Overview         string             `json:"overview"`
	PosterUrl        string             `json:"poster_url"`
	BackdropUrl      string             `json:"backdrop_url"`
	ProviderID       pgtype.UUID        `json:"provider_id"`
	ExternalID       string             `json:"external_id"`
	LicenseUrl       string             `json:"license_url"`
	Rights           string             `json:"rights"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ReleaseDate      pgtype.Date        `json:"release_date"`
	OriginalLanguage string             `json:"original_language"`
	TmdbID           pgtype.Int4        `json:"tmdb_id"`
	SeasonCount      int32              `json:"season_count"`
	EpisodeCount     int32              `json:"episode_count"`
}

type Provider struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Enabled   bool               `json:"enabled"`
	Priority  int32              `json:"priority"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Season struct {
	ID           pgtype.UUID        `json:"id"`
	MediaID      pgtype.UUID        `json:"media_id"`
	SeasonNumber int32              `json:"season_number"`
	Name         string             `json:"name"`
	Overview     string             `json:"overview"`
	PosterUrl    string             `json:"poster_url"`
	AirDate      pgtype.Date        `json:"air_date"`
	EpisodeCount int32              `json:"episode_count"`
	ExternalID   string             `json:"external_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Source struct {
	ID            pgtype.UUID        `json:"id"`
	MediaID       pgtype.UUID        `json:"media_id"`
	ProviderID    pgtype.UUID        `json:"provider_id"`
	ExternalID    string             `json:"external_id"`
	FileName      string             `json:"file_name"`
	OriginalUrl   string             `json:"original_url"`
	Quality       string             `json:"quality"`
	Container     string             `json:"container"`
	VideoCodec    string             `json:"video_codec"`
	AudioCodec    string             `json:"audio_codec"`
	Bitrate       pgtype.Int8        `json:"bitrate"`
	DirectPlay    bool               `json:"direct_play"`
	RequiresProxy bool               `json:"requires_proxy"`
	Status        string             `json:"status"`
	LastCheckedAt pgtype.Timestamptz `json:"last_checked_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type SourceHealth struct {
	SourceID      pgtype.UUID        `json:"source_id"`
	Status        string             `json:"status"`
	HttpStatus    pgtype.Int4        `json:"http_status"`
	LatencyMs     pgtype.Int4        `json:"latency_ms"`
	LastSuccessAt pgtype.Timestamptz `json:"last_success_at"`
	LastFailureAt pgtype.Timestamptz `json:"last_failure_at"`
	CheckedAt     pgtype.Timestamptz `json:"checked_at"`
}
