// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addLibraryItem = `-- name: AddLibraryItem :exec
INSERT INTO library_items(media_id) VALUES($1) ON CONFLICT(media_id) DO NOTHING
`

func (q *Queries) AddLibraryItem(ctx context.Context, mediaID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, addLibraryItem, mediaID)
	return err
}

const getMediaByExternalID = `-- name: GetMediaByExternalID :one
SELECT m.id, m.type, m.title, m.original_title, m.year, m.overview, m.poster_url, m.backdrop_url, m.provider_id, m.external_id, m.license_url, m.rights, m.created_at, m.updated_at FROM media m JOIN providers p ON p.id=m.provider_id WHERE p.name=$1 AND m.external_id=$2
`

type GetMediaByExternalIDParams struct {
	Name       string `json:"name"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetMediaByExternalID(ctx context.Context, arg GetMediaByExternalIDParams) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByExternalID, arg.Name, arg.ExternalID)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.OriginalTitle,
		&i.Year,
		&i.Overview,
		&i.PosterUrl,
		&i.BackdropUrl,
		&i.ProviderID,
		&i.ExternalID,
		&i.LicenseUrl,
		&i.Rights,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, type, title, original_title, year, overview, poster_url, backdrop_url, provider_id, external_id, license_url, rights, created_at, updated_at FROM media WHERE id = $1
`

func (q *Queries) GetMediaByID(ctx context.Context, id pgtype.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.OriginalTitle,
		&i.Year,
		&i.Overview,
		&i.PosterUrl,
		&i.BackdropUrl,
		&i.ProviderID,
		&i.ExternalID,
		&i.LicenseUrl,
		&i.Rights,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, name, type, enabled, priority, created_at, updated_at FROM providers WHERE id=$1 AND enabled=true
`

func (q *Queries) GetProviderByID(ctx context.Context, id pgtype.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderByName = `-- name: GetProviderByName :one
SELECT id, name, type, enabled, priority, created_at, updated_at FROM providers WHERE name = $1 AND enabled = true
`

func (q *Queries) GetProviderByName(ctx context.Context, name string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByName, name)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSourceByID = `-- name: GetSourceByID :one
SELECT id, media_id, provider_id, external_id, file_name, original_url, quality, container, video_codec, audio_codec, bitrate, direct_play, requires_proxy, status, last_checked_at, created_at, updated_at FROM sources WHERE id=$1 AND status='available'
`

func (q *Queries) GetSourceByID(ctx context.Context, id pgtype.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByID, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.ProviderID,
		&i.ExternalID,
		&i.FileName,
		&i.OriginalUrl,
		&i.Quality,
		&i.Container,
		&i.VideoCodec,
		&i.AudioCodec,
		&i.Bitrate,
		&i.DirectPlay,
		&i.RequiresProxy,
		&i.Status,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSourcesByMediaID = `-- name: GetSourcesByMediaID :many
SELECT id, media_id, provider_id, external_id, file_name, original_url, quality, container, video_codec, audio_codec, bitrate, direct_play, requires_proxy, status, last_checked_at, created_at, updated_at FROM sources WHERE media_id=$1 AND status='available' ORDER BY direct_play DESC, CASE container WHEN 'mp4' THEN 0 WHEN 'm4v' THEN 1 WHEN 'mov' THEN 2 WHEN 'webm' THEN 3 WHEN 'mkv' THEN 4 ELSE 5 END, CASE WHEN quality ~ '^[0-9]+p$' THEN substring(quality from '^[0-9]+')::int ELSE 0 END DESC, file_name
`

func (q *Queries) GetSourcesByMediaID(ctx context.Context, mediaID pgtype.UUID) ([]Source, error) {
	rows, err := q.db.Query(ctx, getSourcesByMediaID, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.ProviderID,
			&i.ExternalID,
			&i.FileName,
			&i.OriginalUrl,
			&i.Quality,
			&i.Container,
			&i.VideoCodec,
			&i.AudioCodec,
			&i.Bitrate,
			&i.DirectPlay,
			&i.RequiresProxy,
			&i.Status,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryItems = `-- name: ListLibraryItems :many
SELECT m.id, m.type, m.title, m.original_title, m.year, m.overview, m.poster_url, m.backdrop_url, m.provider_id, m.external_id, m.license_url, m.rights, m.created_at, m.updated_at FROM library_items li JOIN media m ON m.id=li.media_id ORDER BY li.created_at DESC LIMIT $1 OFFSET $2
`

type ListLibraryItemsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLibraryItems(ctx context.Context, arg ListLibraryItemsParams) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listLibraryItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.OriginalTitle,
			&i.Year,
			&i.Overview,
			&i.PosterUrl,
			&i.BackdropUrl,
			&i.ProviderID,
			&i.ExternalID,
			&i.LicenseUrl,
			&i.Rights,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, type, enabled, priority, created_at, updated_at FROM providers WHERE enabled = true ORDER BY priority DESC, name
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeLibraryItem = `-- name: RemoveLibraryItem :exec
DELETE FROM library_items WHERE media_id=$1
`

func (q *Queries) RemoveLibraryItem(ctx context.Context, mediaID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeLibraryItem, mediaID)
	return err
}

const upsertMedia = `-- name: UpsertMedia :one
INSERT INTO media(type,title,original_title,year,overview,poster_url,backdrop_url,provider_id,external_id,license_url,rights)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
ON CONFLICT(provider_id,external_id) DO UPDATE SET type=excluded.type,title=excluded.title,original_title=excluded.original_title,year=excluded.year,overview=excluded.overview,poster_url=excluded.poster_url,backdrop_url=excluded.backdrop_url,license_url=excluded.license_url,rights=excluded.rights,updated_at=now()
RETURNING id, type, title, original_title, year, overview, poster_url, backdrop_url, provider_id, external_id, license_url, rights, created_at, updated_at
`

type UpsertMediaParams struct {
	Type          string      `json:"type"`
	Title         string      `json:"title"`
	OriginalTitle string      `json:"original_title"`
	Year          pgtype.Int4 `json:"year"`
	Overview      string      `json:"overview"`
	PosterUrl     string      `json:"poster_url"`
	BackdropUrl   string      `json:"backdrop_url"`
	ProviderID    pgtype.UUID `json:"provider_id"`
	ExternalID    string      `json:"external_id"`
	LicenseUrl    string      `json:"license_url"`
	Rights        string      `json:"rights"`
}

func (q *Queries) UpsertMedia(ctx context.Context, arg UpsertMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, upsertMedia,
		arg.Type,
		arg.Title,
		arg.OriginalTitle,
		arg.Year,
		arg.Overview,
		arg.PosterUrl,
		arg.BackdropUrl,
		arg.ProviderID,
		arg.ExternalID,
		arg.LicenseUrl,
		arg.Rights,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.OriginalTitle,
		&i.Year,
		&i.Overview,
		&i.PosterUrl,
		&i.BackdropUrl,
		&i.ProviderID,
		&i.ExternalID,
		&i.LicenseUrl,
		&i.Rights,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSource = `-- name: UpsertSource :one
INSERT INTO sources(media_id,provider_id,external_id,file_name,original_url,quality,container,video_codec,audio_codec,bitrate,direct_play,requires_proxy,status)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'available')
ON CONFLICT(provider_id,external_id,file_name) DO UPDATE SET media_id=excluded.media_id,original_url=excluded.original_url,quality=excluded.quality,container=excluded.container,video_codec=excluded.video_codec,audio_codec=excluded.audio_codec,bitrate=excluded.bitrate,direct_play=excluded.direct_play,requires_proxy=excluded.requires_proxy,status='available',updated_at=now()
RETURNING id, media_id, provider_id, external_id, file_name, original_url, quality, container, video_codec, audio_codec, bitrate, direct_play, requires_proxy, status, last_checked_at, created_at, updated_at
`

type UpsertSourceParams struct {
	MediaID       pgtype.UUID `json:"media_id"`
	ProviderID    pgtype.UUID `json:"provider_id"`
	ExternalID    string      `json:"external_id"`
	FileName      string      `json:"file_name"`
	OriginalUrl   string      `json:"original_url"`
	Quality       string      `json:"quality"`
	Container     string      `json:"container"`
	VideoCodec    string      `json:"video_codec"`
	AudioCodec    string      `json:"audio_codec"`
	Bitrate       pgtype.Int8 `json:"bitrate"`
	DirectPlay    bool        `json:"direct_play"`
	RequiresProxy bool        `json:"requires_proxy"`
}

func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, upsertSource,
		arg.MediaID,
		arg.ProviderID,
		arg.ExternalID,
		arg.FileName,
		arg.OriginalUrl,
		arg.Quality,
		arg.Container,
		arg.VideoCodec,
		arg.AudioCodec,
		arg.Bitrate,
		arg.DirectPlay,
		arg.RequiresProxy,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.ProviderID,
		&i.ExternalID,
		&i.FileName,
		&i.OriginalUrl,
		&i.Quality,
		&i.Container,
		&i.VideoCodec,
		&i.AudioCodec,
		&i.Bitrate,
		&i.DirectPlay,
		&i.RequiresProxy,
		&i.Status,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
